# Generated by Django 4.0.4 on 2022-05-23 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_job_description_alter_job_job_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='exeperince',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='job',
            name='published_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='job',
            name='salary',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='job',
            name='vacance',
            field=models.IntegerField(default=1),
        ),
    ]
